AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Inspection - Centralized Outbound with a Region without Inspection (Global Network & Core Network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Centralized Outbound
      Tags: 
        - Key: Name
          Value: global-network-centralized-outbound
  
  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Centralized Outbound
      GlobalNetworkId: !Ref GlobalNetwork
      Tags: 
        - Key: Name
          Value: core-network-centralized-outbound
      PolicyDocument: 
        version: "2021.12"
        core-network-configuration:
          vpn-ecmp-support: false
          asn-ranges:
            - 64520-65525
          edge-locations:
            - location: eu-west-1
            - location: eu-west-2
            - location: us-east-1
            - location: ap-southeast-2
        segments:
          - name: production
            require-attachment-acceptance: false
            isolate-attachments: true
          - name: development
            require-attachment-acceptance: false
        network-function-groups:
          - name: inspectionVpcs
            require-attachment-acceptance: false
        attachment-policies:
          - rule-number: 100
            conditions:
              - type: tag-value
                operator: equals
                key: inspection
                value: true
            action:
              add-to-network-function-group: inspectionVpcs
          - rule-number: 200
            conditions:
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
        segment-actions:
          - action: send-to
            segment: production
            via:
              network-function-groups:
                - inspectionVpcs
              with-edge-overrides:
                - edge-sets:
                    - - eu-west-2
                  use-edge-location: eu-west-1
          - action: send-to
            segment: development
            via:
              network-function-groups:
                - inspectionVpcs
              with-edge-overrides:
                - edge-sets:
                    - - eu-west-2
                  use-edge-location: eu-west-1